import "@fhevm/hardhat-plugin";
import "@nomicfoundation/hardhat-chai-matchers";
import "@nomicfoundation/hardhat-ethers";
import "@nomicfoundation/hardhat-verify";
import "@typechain/hardhat";
import { vars } from "hardhat/config";
import type { HardhatUserConfig } from "hardhat/config";
import * as fs from "fs";
import * as path from "path";

// Signer and RPC, in order: env, then probe/secrets.json (git-ignored).
// Same convention as GhostLend so the funded probe wallet carries over.
type Secrets = { privateKey?: string; sepoliaRpcUrl?: string };
let fileSecrets: Secrets = {};
try {
  const p = path.join(__dirname, "probe", "secrets.json");
  if (fs.existsSync(p)) fileSecrets = JSON.parse(fs.readFileSync(p, "utf8")) as Secrets;
} catch {
  /* ignore */
}

const PK: string = process.env.PROBE_PK || fileSecrets.privateKey || "";
const RPC: string =
  process.env.SEPOLIA_RPC_URL ||
  fileSecrets.sepoliaRpcUrl ||
  "https://ethereum-sepolia-rpc.publicnode.com";

const config: HardhatUserConfig = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: { chainId: 31337 },
    sepolia: {
      accounts: PK ? [PK.startsWith("0x") ? PK : `0x${PK}`] : [],
      chainId: 11155111,
      url: RPC,
    },
  },
  // Verification was missing entirely, so a judge clicking through to Etherscan
  // met raw bytecode. A single-key string makes hardhat-verify use the V2
  // multichain endpoint; the per-network object form targets the deprecated V1.
  etherscan: {
    apiKey: vars.get("ETHERSCAN_API_KEY", ""),
  },
  paths: { artifacts: "./artifacts", cache: "./cache", sources: "./contracts", tests: "./test" },
  typechain: { outDir: "types", target: "ethers-v6" },
  solidity: {
    compilers: [
      {
        version: "0.8.27",
        settings: {
          metadata: { bytecodeHash: "none" },
          optimizer: { enabled: true, runs: 800 },
          evmVersion: "cancun",
        },
      },
    ],
    // SaveTogetherSession's clamp chains overflow the legacy stack allocator and
    // only compile through the IR pipeline. It is an override rather than a
    // global setting on purpose: viaIR changes generated bytecode, and the
    // pool's 306-sample gas measurement was taken against a build without it.
    // Turning it on everywhere would quietly invalidate that result.
    overrides: {
      "contracts/SaveTogetherSession.sol": {
        version: "0.8.27",
        settings: {
          metadata: { bytecodeHash: "none" },
          optimizer: { enabled: true, runs: 800 },
          viaIR: true,
          evmVersion: "cancun",
        },
      },
    },
  },
};

export default config;
